server:
  port: 10001

spring:
  datasource:
    username: root
    password: mysql@123
    url: jdbc:mysql://101.34.94.242:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 101.34.94.242:8848

  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.atguigu.gulimall: debug
