server:
  port: 9000

spring:
  datasource:
    username: root
    password: mysql@123
    url: jdbc:mysql://101.34.94.242/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 101.34.94.242:8848
  application:
    name: gulimall-order

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

