spring:
  application:
    name: gulimall-third-party
  alicloud:
    host: http://notifysms.market.alicloudapi.com
    path: /send
    template-code: T0001
    sign-name: 复数科技
    app-code: edeaeaffceeb4d158fc779a8c298bd66

server:
  port: 30000
